dist: xenial
language: ruby
rvm:
  - 2.5.3
sudo: false

cache: bundler # caching bundler gem packages will speed up build

addons:
  apt:
    packages:
    - lftp
branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/proof.sh
  - chmod +x ./scripts/deploy.sh

script:
  - ./scripts/build.sh
  - ./scripts/proof.sh

after_success:
  - ./scripts/deploy.sh
