# Site settings
title: Association des sociétés techniques de Polytechnique
title-short: ASTP
description: >
    Blah blah
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Author
author-name: Christophe Bédard
author-email: christophe.bedard@polymtl.ca # TODO include somewhere along with author-name

# Contact info
email: societestechniques@polymtl.ca 
facebook: TODO

# Build settings
markdown: kramdown

# Exclude list
exclude: [vendor, scripts, README.md, _site, _data, LICENSE, Gemfile, Gemfile.lock]
